apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: docs-test-svc
  description: The place to be, for great artists
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: production
  owner: devops
  
